image: node:16.15-alpine3.14

stages: [build, qa, test, publish]

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

build:
  stage: build
  script:
    - yarn install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/
  only:
    - merge_requests
    - main

qa-eslint:
  dependencies:
    - build
  when: always
  stage: qa
  script:
    - yarn lint:ci
  artifacts:
    when: always
    reports:
      junit: eslint-report.xml
  only:
    - merge_requests

test-jest:
  dependencies:
    - build
  when: always
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - yarn test:unit:ci
  artifacts:
    when: always
    reports:
      junit: jest-report.xml
      coverage_report:
        coverage_format: cobertura
        path: .coverage/cobertura-coverage.xml
  only:
    - merge_requests
    - main

pages:
  stage: publish
  script:
    - yarn install
    - yarn build
    - rm -rf public
    - mkdir public
    - cp -r dist/spa/* public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG
