git:
  changelog: false
  requireBranch: main
  requireCleanWorkingDir: false
  requireUpstream: false
  commitMessage: 'Prepare ${version}'
  tagName: '${version}'
  tagAnnotation: 'Release v${version}'
  tagMatch: '[0-9].[0-9].[0-9]*'
#gitlab:
#  skipChecks: true
#  release: true
npm:
  publish: false
plugins:
  '@release-it/keep-a-changelog':
    filename: CHANGELOG.md
    head: main
    strictLatest: false
    addVersionUrl: true
    versionUrlFormats:
      repositoryUrl: 'https://gitlab.com/sparda-of-nosgoth/mhrs-talismans-manager'
      unreleasedUrl: '{repositoryUrl}/-/compare/{tagName}...{head}'
      versionUrl: '{repositoryUrl}/-/compare/{previousTag}...{tagName}'
      firstVersionUrl: '{repositoryUrl}/-/tags/{tagName}'
