git:
  requireBranch: main
  requireCleanWorkingDir: false
  requireUpstream: false
  commitMessage: 'Release ${version}'
  tagName: '${version}'
  tagMatch: '[0-9]*\.[0-9]*\.[0-9]*'
npm:
  publish: false
plugins:
  '@release-it/keep-a-changelog':
    filename: CHANGELOG.md
    head: main
    strictLatest: false
    keepUnreleased: false
    versionUrlFormats:
      repositoryUrl: 'https://gitlab.com/sparda-of-nosgoth/mhrs-talismans-manager/'
      unreleasedUrl: '{repositoryUrl}/-/compare/{head}...{tagName}'
      versionUrl: '{repositoryUrl}/-/compare/{previousTag}...{tagName}'
      firstVersionUrl: '{repositoryUrl}/-/tags/{tagName}'
